### ISSUE TITLE
Add some functionality like scandir

### ISSUE THREAD

**Issue by soroshsabz** [boostorg/filesystem#132]
ITNOA

Hi,

Many times we need to scanning directory instead of iterating of directories to see all directory with specific order like alphabetically or based on modified time or …

So I think it is useful feature to boost::filesystem provide scan directories

thanks for great library

**Comment by Lastique** [comment]
I think this is better implemented on top of `directory_iterator`. `scandir` exists because C has rather limited standard library, in C++ you can simply do something like this:

```
std::set<path> paths;
std::copy(directory_iterator(dir), directory_iterator(), std::inserter(paths));
```

**Comment by soroshsabz** [comment]
Thanks for response, I think the main difference is performance, because in iterating, boost use readdir in internal implementation, and I think scandir is faster than readdir step by step for scanning usage.

**Comment by Lastique** [comment]
`scandir` is also most likely using `readdir` or the underlying syscall internally. See it in [glibc](https://sourceware.org/git/?p=glibc.git;a=blob;f=dirent/scandir-tail-common.c;h=65853842c1f212376cfcb729c0c383935a0fbedb;hb=refs/heads/master) for instance. I would say, using C++ tools for this has better potential performance because of more aggressive inlining, although the raw code performance is probably offset by `readdir` cost.
