### ISSUE TITLE
Question: creating boost::filesystem::path from std::filesystem::path

### ISSUE THREAD

**Issue by daravi** [boostorg/filesystem#171]
Hello, I was wondering if there is a technical reason that `boost::filesystem::path`'s constructor has not been updated to accept a `std::filesystem::path` as the argument? If this has not been considered before I would like to suggest adding this overload which would make it easier to use boost types that need a `boost::filesystem::path`.

**Comment by Lastique** [comment]
The reason is that conversion between `boost::filesystem::path` and `std::filesystem::path` (in either direction) would require deep copying the path contents, which can be considered expensive. Making the conversion implicit could result in subtle performance issues. However, I'm open to discussion on the mailing list.

There are also differences in behavior in some corner cases between Boost and std, so the conversion could result in surprises.

**Comment by daravi** [comment]
Ok I will follow up on the mailing list then. Thanks.
