### ISSUE TITLE
Construct from std::string_view

### ISSUE THREAD

**Issue by Aleksmia** [boostorg/filesystem#208]
The code below is impossible because boost::filesystem doesn't support construction from std::string_view:

```c++
namespace` fs = boost::filesystem;

constexpr std::string_view fname = "file.txt";
fs::path some_dir = "~/dir";

fs::path full_path = some_dir / fname;
```

One of the possible solutions is the add `std::string_view` to `path_traits::is_pathable`

What are the reasons not to support std::string_view like the `pathable` type?
Probably it has more relevant solution than I suggested?

PS
I can prepare the PR for releasing this feature. May be it will be useful someone else.

**Comment by Lastique** [comment]
> What are the reasons not to support `std::string_view` like the `pathable` type?

Because noone got around to support it. Same with `boost::string_view`.

I should mention that I don't really like how `path_traits` is implemented, especially that it brings in too many unnecessary dependencies. Adding more dependencies is not something I would like, the whole thing should be deprecated and redesigned to work for arbitrary sequences of characters that support `data`, `begin` and `end`. When that will happen, I cannot tell as there are other things pending in Boost.Filesystem.

**Comment by Lastique** [comment]
PRs are welcome, of course, but I can't promise I will merge it. I haven't thought out how `path_traits` should look like myself. :)
