### ISSUE TITLE
v1.81.0:  `boost::filesystem::relative()` giving unexpected results on Windows. 

### ISSUE THREAD

**Issue by lbarbieri** [boostorg/filesystem#325]
The following returns an empty `path` on Windows for v1.81.0:

Precondition:  `baseDir` exists.
```c++
namespace fs = boost::filesystem;
const fs::path testMe = fs::weakly_canonical("c:/path/to/file.txt");
const fs::path baseDir = fs::weakly_canonical("C:/path/to");
if (!fs::is_directory(baseDir)) std::cout << "baseDir does not exist, may affect results" << std::endl;
const auto &rel = fs::relative(testMe, baseDir);
std::cout << "testMe = " << testMe.string() << ", baseDir = " << baseDir << std::endl;
std::cout << "rel.empty() = " << rel.empty() << ", rel = " << rel << std::endl;
```
Observed:
- `rel` is an empty path.  Output is:
    ```txt
    testMe = c:\path\to\file.txt, baseDir = "C:\path\to"
    rel.empty() = 1, rel = ""
    ```
Expected:
- `rel` should be `file.txt`.

Changing `fs` to `std::filesystem` outputs:
```txt
testMe = C:\path\to\file.txt, baseDir = "C:\\path\\to"
rel.empty() = 0, rel = "file.txt"
```

Boost:  v1.81.0

Windows:
    Windows 11
    Version 23H2 (OS Build 22631.4169)

MSVC:
    v17, 2022 Community, 14.41.34120, x64 target, c++17

**Comment by Lastique** [comment]
This is because "c:" (lower-case) and "C:" (upper-case) are considered different root names. Which means the two paths are considered unrelated, so the resulting path is an empty path. If you change the case to be the same the behavior becomes as you expect.

This behavior follows from [`path::lexically_relative`](https://www.boost.org/doc/libs/1_86_0/libs/filesystem/doc/reference.html#lexically_relative) description, which is used by the standalone `relative` operation internally. `path::lexically_relative` uses `operator==` between path elements to determine if they are the same, and that operator is always case-sensitive, even on Windows. This makes sense for file names, since they may indeed be case-sensitive on Windows. I'm not sure if there is an instance when root-names are case-sensitive, though.

Interestingly, [`std::path::lexically_relative`](http://eel.is/c++draft/fs.class.path#fs.path.gen-3) is also defined in terms of comparing path elements, which is also [case-sensitive](http://eel.is/c++draft/fs.class.path#fs.path.compare), so std::filesystem should behave the same. I'm guessing your implementation is performing case-insensitive comparison at some point, which I don't think is compliant.

I admit this may be surprising on Windows, but that's how it is specified.

**Comment by Lastique** [comment]
It looks like MSVC standard library uses [`GetFinalPathNameByHandleW`](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getfinalpathnamebyhandlew) to implement `canonical`, which is called by `weakly_canonical`. That function converts drive letters to upper case, which allows the subsequent comparisons in `path::lexically_relative` to succeed. Perhaps, we should do the same on Windows. This would require Windows Vista at the minimum, but this will be acceptable in Boost 1.87.0 since we're removing support for Windows versions older than 10 in that release anyway.

**Comment by Lastique** [comment]
Should be fixed in develop now. Thank you for the report.
